apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohammadsali/devops-demo.git
    targetRevision: develop
    path: apps/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: demoapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
